include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
    sort_pub_dependencies: false
    sort_unnamed_constructors_first: false

analyzer:
  exclude:
    - '**/*_generated.dart'
    - '**/*.g.dart'